"""rename

Revision ID: 7917fa4dd6cf
Revises: d05f40fbe5e9
Create Date: 2023-12-03 06:59:50.974634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7917fa4dd6cf'
down_revision: Union[str, None] = 'd05f40fbe5e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('result', sa.Column('speed', sa.Integer(), nullable=True))
    op.drop_column('result', 'time')
    op.add_column('tier', sa.Column('speed_ratio', sa.Float(), nullable=True))
    op.drop_column('tier', 'time_ratio')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tier', sa.Column('time_ratio', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('tier', 'speed_ratio')
    op.add_column('result', sa.Column('time', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('result', 'speed')
    # ### end Alembic commands ###
