"""add tier model

Revision ID: d05f40fbe5e9
Revises: 35231e8beeef
Create Date: 2023-12-03 06:58:51.255146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd05f40fbe5e9'
down_revision: Union[str, None] = '35231e8beeef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=True),
    sa.Column('time_ratio', sa.Float(), nullable=True),
    sa.Column('correct_rate_ratio', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'text', 'tier', ['tier'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'text', type_='foreignkey')
    op.drop_table('tier')
    # ### end Alembic commands ###
